### ISSUE TITLE
Add SHA256 git support to Gitea

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/openSUSE-git#16]
The current default of SHA1 in distributed per-package gits could be potentially too weak as it allows for collision attacks (collisions are only avoided on a per repo basis). To mitigate that we could start with sha256 gits right away. The alternative would be monorepo, which however many dislike.

Gitea currently is not able to support SHA256. We need to add support.

**Comment by dirkmueller** [comment]
@AdamMajer has started an implementation upstream: https://github.com/go-gitea/gitea/pull/23894

**Comment by AdamMajer** [comment]
update: The workaround for cloning empty sha256 repos is to use env variable GIT_DEFAULT_HASH=sha256 to setup the clone correctly.

**Comment by JanZerebecki** [comment]
While not the best decision security wise, I lean towards stick with the git default of sha1 for now:
* no risk of tripping over something that hinders our move
* no risk of needing to rewrite history if some incompatibility with the existing sha256 implementation happens
* we do not prevent us from adopting workflows that directly combine with upstream repos, which will mostly be sha1 (this seems to be the only heavy reason in favor sticking with sha1)
* we might be able to adapt git-evtag for commits if we need to be compliant before migration is ready
* we need someone to implement the migration in upstream git anyway, without that the risk of sha1 still exists in upstream repos
