### ISSUE TITLE
Test gitea-actions

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/openSUSE-git#25]
Gitea 1.19 added an experimental feature called "gitea-actions" which is a CI/CD system modelled after Git Hub Actions. We should test it out by making it test builds of PRs against a package repository.

**Comment by AvengerMoJo** [comment]
It is working now. https://src.opensuse.org/alexlau/gitea-actions-test/actions/runs/2

**Comment by celan** [comment]
Seems to work and has been adopted by different teams, including Maintenance. Please close it. I don't have the permissions.

**Comment by celan** [comment]
This is works. See above.
